// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Structured agent identity surfaced to frontends.
 */
export type AgentIdentity = { 
/**
 * Stable agent UUID inside the current runtime tree.
 */
agent_id: string, 
/**
 * Internal durable label used by SA for this agent.
 */
agent_label: string, 
/**
 * User-facing display name the frontend should render.
 */
display_name: string, 
/**
 * Whether this identity belongs to the root "学习委员" agent.
 */
is_root: boolean, };
