// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Authentication style used when sending requests to the configured provider.
 *
 * Why make this explicit?
 * - OpenAI-style gateways normally expect `Authorization: Bearer ...`
 * - Anthropic-style gateways normally expect `x-api-key: ...`
 * - Anthropic setup-token / OAuth flows instead expect `Authorization`
 * - some vendors proxy Anthropic but keep Anthropic auth semantics
 */
export type AuthStyle = "Bearer" | "XApiKey" | "AnthropicAuto";
