// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ClientHello } from "./ClientHello";
import type { InitializeConfigRequest } from "./InitializeConfigRequest";
import type { UserQuestionAnswer } from "./UserQuestionAnswer";

/**
 * Client -> server messages.
 */
export type ClientMessage = { "type": "client_hello", hello: ClientHello, } | { "type": "submit", 
/**
 * Client-generated task id for idempotent retries.
 */
task_id: string | null, 
/**
 * The task text for the agent.
 */
task: string, } | { "type": "get_history", from_event_id: bigint, } | { "type": "interrupt", task_id: string, } | { "type": "answer_question", answer: UserQuestionAnswer, } | { "type": "initialize_config", request: InitializeConfigRequest, } | { "type": "image_upload", 
/**
 * Client-generated upload id for correlation.
 */
upload_id: string, 
/**
 * Original filename provided by the user (for extension detection only).
 */
filename: string, 
/**
 * MIME type hint, e.g. "image/png", "image/jpeg".
 */
mime_type: string, 
/**
 * Base64-encoded image bytes.
 */
data: string, 
/**
 * Optional task id to attach the image to. If None, the image will
 * be associated with the next submitted task.
 */
task_id: string | null, } | { "type": "get_config" } | { "type": "update_config", 
/**
 * The complete configuration as a JSON object matching the `sa.toml`
 * schema. Sensitive fields (api_key) sent as masked values will be
 * replaced by the current real values on the server side.
 */
config: unknown, } | { "type": "get_memory_facts", query: string | null, limit: number, offset: number, } | { "type": "get_memory_stats" } | { "type": "traverse_memory_graph", subject: string, max_hops: number, max_results: number, } | { "type": "decay_memory_facts" } | { "type": "prune_memory_facts", min_confidence: number, };
