// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * The client's proof-of-identity packet.
 */
export type ClientHello = { 
/**
 * Stable protocol identifier (example: `sa-ws/v1`).
 */
protocol: string, 
/**
 * Hash algorithm identifier used by the proofs.
 */
hash_algo: string, 
/**
 * Time bucket width in seconds.
 */
time_step_secs: bigint, 
/**
 * Allowed clock skew in time buckets.
 */
allowed_skew_buckets: bigint, 
/**
 * Expected logical frontend identity name (currently `sa-frontend`).
 */
client_name: string, 
/**
 * Frontend binary version.
 */
client_version: string, 
/**
 * UTC time bucket used to derive the proof.
 */
time_bucket: bigint, 
/**
 * Client-generated nonce to bind the server proof to this exact handshake.
 */
client_nonce: string, 
/**
 * Hex-encoded SHA-256 proof.
 */
proof: string, };
