// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AgentIdentity } from "./AgentIdentity";
import type { EventKind } from "./EventKind";

/**
 * One event emitted by the backend.
 */
export type Event = { 
/**
 * Monotonic event id assigned by the server.
 */
event_id: bigint, 
/**
 * UTC timestamp of the event.
 */
ts: string, 
/**
 * Task that produced the event.
 */
task_id: string, 
/**
 * Event classification used by the UI.
 */
kind: EventKind, 
/**
 * Human-readable message.
 */
message: string, 
/**
 * Optional structured sender identity for frontend rendering.
 */
agent: AgentIdentity | null, };
