// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Rejection payload returned when the mandatory handshake fails.
 */
export type HelloReject = { 
/**
 * Stable protocol identifier.
 */
protocol: string, 
/**
 * Server name emitting the rejection.
 */
server_name: string, 
/**
 * Server binary version.
 */
server_version: string, 
/**
 * Human-readable rejection reason.
 */
reason: string, };
