// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * First-run initialization methods offered by the backend.
 */
export type InitMethod = "open_ai_compatible" | "anthropic_compatible" | "custom";
