// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Positive confirmation returned after first-run initialization succeeds.
 */
export type InitCompleted = { 
/**
 * Absolute path where the backend wrote the new `sa.toml`.
 */
config_path: string, 
/**
 * Workspace root activated by the new runtime.
 */
workspace_root: string, 
/**
 * Human-readable summary for the frontend.
 */
message: string, };
