// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Structured initialization error returned to the frontend.
 */
export type InitFailed = { 
/**
 * Short user-facing summary.
 */
message: string, 
/**
 * Optional detailed diagnostic text.
 */
detail: string | null, };
