// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { InitMethod } from "./InitMethod";
import type { InitMethodOption } from "./InitMethodOption";

/**
 * Message sent by the backend when `sa.toml` is missing.
 */
export type InitRequired = { 
/**
 * Absolute path where the backend expects `sa.toml`.
 */
config_path: string, 
/**
 * Workspace root the generated config will point at.
 */
workspace_root: string, 
/**
 * `Agents.md` path the generated config will use.
 */
agents_md_path: string, 
/**
 * Supported initialization methods the frontend should render.
 */
methods: Array<InitMethodOption>, 
/**
 * Recommended method to preselect on the frontend.
 */
recommended_method: InitMethod, };
