// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AuthStyle } from "./AuthStyle";
import type { InitMethod } from "./InitMethod";
import type { WireApi } from "./WireApi";

/**
 * One frontend-visible initialization option card.
 */
export type InitMethodOption = { 
/**
 * Stable option id.
 */
id: InitMethod, 
/**
 * User-facing label.
 */
label: string, 
/**
 * Explanatory help text.
 */
description: string, 
/**
 * Recommended default wire protocol for this option.
 */
default_wire_api: WireApi, 
/**
 * Recommended default auth style for this option.
 */
default_auth_style: AuthStyle, 
/**
 * Recommended role name for the prompt prefix message.
 */
default_system_role_name: string, 
/**
 * Whether this option should be highlighted as the recommended path.
 */
recommended: boolean, };
