// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * A single semantic fact for wire transfer.
 */
export type MemoryFact = { id: string, subject: string, predicate: string, object: string, confidence: number, source: string | null, created_at: string, updated_at: string, };
