// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * One selectable option inside a structured question.
 */
export type QuestionOption = { 
/**
 * Stable option id used in answers.
 */
id: string, 
/**
 * User-facing label.
 */
label: string, 
/**
 * Optional descriptive help text.
 */
description: string | null, };
