// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * How the user should answer the question.
 */
export type QuestionMode = "single_choice" | "multi_choice" | "text";
