// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Event } from "./Event";
import type { HelloReject } from "./HelloReject";
import type { InitCompleted } from "./InitCompleted";
import type { InitFailed } from "./InitFailed";
import type { InitRequired } from "./InitRequired";
import type { MemoryFact } from "./MemoryFact";
import type { ServerHello } from "./ServerHello";
import type { UserQuestion } from "./UserQuestion";
import type { UserVisibleFile } from "./UserVisibleFile";

/**
 * Server -> client messages.
 */
export type ServerMessage = { "type": "server_hello", hello: ServerHello, } | { "type": "hello_reject", reject: HelloReject, } | { "type": "accepted", task_id: string, } | { "type": "history", events: Array<Event>, } | { "type": "event", event: Event, } | { "type": "question", question: UserQuestion, } | { "type": "pending_questions", questions: Array<UserQuestion>, } | { "type": "question_resolved", question_id: string, } | { "type": "show", file: UserVisibleFile, } | { "type": "recent_shows", files: Array<UserVisibleFile>, } | { "type": "init_required", request: InitRequired, } | { "type": "init_completed", info: InitCompleted, } | { "type": "init_failed", error: InitFailed, } | { "type": "error", message: string, } | { "type": "image_uploaded", 
/**
 * Echoed upload id from the client's `image_upload` message.
 */
upload_id: string, 
/**
 * Absolute workspace path where the image was saved.
 */
saved_path: string, } | { "type": "config_snapshot", 
/**
 * The full config as a JSON value (TOML-compatible).
 */
config: unknown, 
/**
 * Absolute path to the `sa.toml` file on disk.
 */
config_path: string, } | { "type": "config_updated", 
/**
 * Human-readable summary of what changed.
 */
summary: string, } | { "type": "config_update_failed", 
/**
 * Short user-facing error message.
 */
message: string, 
/**
 * Optional detailed diagnostic text.
 */
detail: string | null, } | { "type": "memory_facts", facts: Array<MemoryFact>, total: number, offset: number, } | { "type": "memory_graph", subject: string, facts: Array<MemoryFact>, hops: number, } | { "type": "memory_stats", total_facts: number, unique_subjects: number, unique_predicates: number, avg_confidence: number, oldest_fact: string | null, newest_fact: string | null, } | { "type": "memory_operation_result", operation: string, affected: number, summary: string, };
