// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * The server's proof-of-identity packet.
 */
export type ServerHello = { 
/**
 * Stable protocol identifier (example: `sa-ws/v1`).
 */
protocol: string, 
/**
 * Hash algorithm identifier used by the proofs.
 */
hash_algo: string, 
/**
 * Time bucket width in seconds.
 */
time_step_secs: bigint, 
/**
 * Allowed clock skew in time buckets.
 */
allowed_skew_buckets: bigint, 
/**
 * Expected backend name (currently `sa`).
 */
server_name: string, 
/**
 * Backend binary version.
 */
server_version: string, 
/**
 * UTC time bucket used to derive the proof.
 */
time_bucket: bigint, 
/**
 * Best-effort backend machine hint for audit/debugging. This is not part
 * of the proof verification path.
 */
machine_hint: string, 
/**
 * Echo of the client's nonce.
 */
client_nonce: string, 
/**
 * Server-generated nonce.
 */
server_nonce: string, 
/**
 * Hex-encoded SHA-256 proof.
 */
proof: string, };
