// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AgentIdentity } from "./AgentIdentity";
import type { QuestionMode } from "./QuestionMode";
import type { QuestionOption } from "./QuestionOption";

/**
 * Structured question emitted by the backend.
 */
export type UserQuestion = { 
/**
 * Unique question id.
 */
question_id: string, 
/**
 * Top-level task id this question belongs to.
 */
task_id: string, 
/**
 * Backend-side creation time used by reconnecting frontends to restore
 * the original ordering around blocking `Ask` messages.
 */
created_at: string, 
/**
 * Agent identity that issued this question.
 */
agent: AgentIdentity | null, 
/**
 * User-facing prompt.
 */
prompt: string, 
/**
 * Expected answer shape.
 */
mode: QuestionMode, 
/**
 * Choice options for non-text questions.
 */
options: Array<QuestionOption>, 
/**
 * Whether extra free text is allowed.
 */
allow_free_text: boolean, };
