// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * User answer sent back to the backend.
 */
export type UserQuestionAnswer = { 
/**
 * Which question this answers.
 */
question_id: string, 
/**
 * Selected option ids, if any.
 */
selected_option_ids: Array<string>, 
/**
 * Optional free-text payload.
 */
free_text: string | null, };
