// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Wire protocol used for one OpenAI-compatible endpoint.
 */
export type WireApi = "ChatCompletions" | "Responses" | "AnthropicMessages";
